### PR TITLE
add READMEs

### PR DESCRIPTION
**Pull request by harshraj8843**
### What's being changed:

`https://github.com/codinasion/codinasion-tools/blob/documentation/README.md`

`https://github.com/codinasion/codinasion-tools/blob/documentation/npm/README.md`

`https://github.com/codinasion/codinasion-tools/blob/documentation/pip/README.md`

### CODE REVIEW

**Comment by harshraj8843** [comment]
Done 🎉

**Comment by 0ME9A** [comment]
License is still 404

**Comment by harshraj8843** [comment]
Will be automatically updated (maybe cache)

https://img.shields.io/github/license/codinasion/codinasion-tools?color=lightgreen

**Comment by 0ME9A** [comment]
Ok 😀

**Comment by 0ME9A** [comment]
Do you know we should also add a share button on the Tid page for sharing and caring, I just realized.😲
But leave it for now just remember this feature. we must adapt it in the future.😊
---
It's party time 🎉🎉🎉

**Comment by harshraj8843** [comment]
Sure 🎉 🥳

**Comment by 0ME9A** [comment]
Add some good vibes.
image

**Comment by harshraj8843** [comment]
How ?

**Comment by harshraj8843** [comment]
okay, but what should be the TEXT 🤔

**Comment by 0ME9A** [comment]
> okay, but what should be the TEXT 🤔

I don't know It's your review😅

**Comment by harshraj8843** [comment]
ok

**Comment by 0ME9A** [comment]
Bro what's the problem, why this site doesn't show our feedback? 🤔

**Comment by harshraj8843** [comment]
Currently there is no way to post testimonials

You have commented https://github.com/codinasion/comments/discussions/17

**Comment by 0ME9A** [comment]
KevinHartGIF

**Comment by harshraj8843** [comment]
Screenshot from 2023-01-14 00-19-25

**Comment by harshraj8843** [comment]
https://github.com/codinasion/codinasion-tools/pull/19/

**Comment by 0ME9A** [comment]
Ok,

So you can add my comment in testimonial API, You are such a god of this org, so do it.😍

**Comment by harshraj8843** [comment]
Already added #19

**Pull request merged**
